[package]
name = "latte"
version = "0.1.0"
authors = ["Maciej Piktel <mp347205@students.mimuw.edu.pl>"]
build = "src/build.rs"

[dependencies.lalrpop-util]
version = "0.12.4"

[build-dependencies.lalrpop]
version = "0.12.4"
